---
  - name: Gather facts
    icx_facts:
      gather_subset: all

  - name: Assemble vlan membership list
    set_fact:
      icx_vlan_membership: "{{ icx_portconfig | vlan_membership(icx_lags) }}"

  - name: Find interfaces already on switch
    set_fact:
      port_status: "{{ ansible_net_config | find_active_interfaces(icx_portconfig, icx_lags) }}"

  - name: Find vlans already on switch
    set_fact:
      vlan_port_status: "{{ ansible_net_config | running_ports_status('vlan') }}"

  - name: Find lags already on switch
    set_fact:
      lag_port_status: "{{ ansible_net_config | running_ports_status('lag') }}"

  - name: Find lags already on switch
    set_fact:
      lag_port_diff: "{{ lag_port_status | lag_ports_diff(icx_lags) }}"

  - name: Find vlans already on switch
    set_fact:
      vlan_port_diff: "{{ vlan_port_status | vlan_ports_diff(icx_vlan_membership) }}"

  - name: Fail on invalid firmware release
    when: icx_expected_firmware != "" and icx_expected_firmware != ansible_net_version
    fail:
      msg: Unexpected firmware revision on device!

  - name: Configure management interface
    icx_config:
      lines:
        - vlan 1
        - router-interface ve 1
    when: icx_is_l3_switch

  - name: Configure management interface
    icx_l3_interface:
      name: ve 1
      ipv4: "{{ icx_mgmt_ip }}"
    when: icx_is_l3_switch

  - name: Configure users
    icx_user:
      aggregate: "{{ icx_users }}"
      purge: "yes"

  - name: System config
    icx_system:
      hostname: "{{ icx_my_name }}"
      domain_name: "{{ icx_domain_name }}"
      name_servers:
        - "{{ icx_nameserver }}"

  - name: General setup
    icx_config:
      lines: "{{ icx_general_config }}"

  - name: General setup (L3 specific)
    icx_config:
      lines: "{{ icx_l3_config }}"
    when: icx_is_l3_switch

  - name: Render and print running config
    debug:
      msg: "{{ ansible_net_config.split('\n') }}"

  - name: Render and print combined vlan/lag/interface config
    debug:
      msg: "{{ lookup('template', 'config.j2').split('\n') }}"

  - name: Render combined vlan/lag/interface config
    icx_config:
      src: "{{ lookup('template', 'config.j2') }}"
      diff_against: "running"
