---
  - name: Gather facts
    icx_facts:
      gather_subset: all

  - name: Fail on invalid firmware release
    when: icx_expected_firmware != "" and icx_expected_firmware != ansible_net_version
    fail:
      msg: Unexpected firmware revision on device!

  - name: Configure management interface
    icx_config:
      lines:
        - vlan 1
        - router-interface ve 1
    when: icx_is_l3_switch

  - name: Configure management interface
    icx_l3_interface:
      name: ve 1
      ipv4: "{{ icx_mgmt_ip }}"
    when: icx_is_l3_switch

  - name: Configure users
    icx_user:
      aggregate: "{{ icx_users }}"
      purge: "yes"

  - name: System config
    icx_system:
      hostname: "{{ icx_my_name }}"
      domain_name: "{{ icx_domain_name }}"
      name_servers:
        - "{{ icx_nameserver }}"

  - name: General setup
    icx_config:
      lines: "{{ icx_general_config }}"

  - name: General setup (L3 specific)
    icx_config:
      lines: "{{ icx_l3_config }}"
    when: icx_is_l3_switch

  - name: Assemble vlan membership list
    set_fact:
      icx_vlan_membership: "{{ icx_portconfig|vlan_membership(icx_lags) }}"

  - name: Render combined vlan/lag/interface config
    icx_config:
      src: "{{ lookup('template', 'config.j2') }}"
